### PR TITLE
feat(plugin): support id as a function

### PR DESCRIPTION
**Pull request by CKGrafico**
id as functions are compatibles but with this commit will also receive app as param. #27

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
This is already possible with `vue-analytics`
https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/installation.md

**Comment by CKGrafico** [comment]
@ricardogobboso maybe I didn't explain it well, the problem is not part of vue analytics.

**Comment by pi0** [comment]
@CKGrafico Why not using normal VueAnalytics id as a function feature. From #27 example, it seems `document` would be enough (PS: We also have `window.$nuxt`)

**Comment by CKGrafico** [comment]
@pi0 because we declare this function in nuxt.config.js and with that we can create the funcion after compilation, in our real case we call to an external API to get some settings (including GA code, becasue our client requested...) that means that now we have to do the ajax call in the id function too but if we have access to app we can pass this parameter in other moment.

**Comment by pi0** [comment]
Can still use `window.$nuxt.$axios` there 🙈

**Comment by CKGrafico** [comment]
@pi0 thanks for your feedback, that's what we actually are using, but the idea is to don't do the ajax call in this point. Is zero maintainable :) 

As I always say, this is not my library if this give value yo you accept it if not it is also ok haha

**Comment by pi0** [comment]
@CKGrafico That's why i kept this issue open. If it adds values to users should be added. Feel free to contact me on discord (@pi0#6582 ) or via email (pooya@pi0.ir) so we can talk more about this.

**Comment by ricardogobbosouza** [comment]
@CKGrafico Now I understand your request
With it we can do this:

```js
googleAnalytics: {
  async id({ $axios }) {
    const { id } = await $axios.$get('/ga')
    return id
  }
}
```

Solve conflicts and create tests or do you want me to do this?

**Comment by CKGrafico** [comment]
Hi @ricardogobbosouza I'm busy this week if you can do it is ok, if not I will need some days

**Pull request closed without merging**
